resources.resource:
  type: config_entity
  label: 'Resource'
  mapping:
    shared:
      id:
        type: string
        label: 'ID'
      title:
        type: label
        label: 'Title'
      url:
        type: string
        label: 'URL'
  constraints:
    id:
      - ConfigEntityIdUnique: []
  keys:
    id: id
  entity_keys:
    id: id
    label: title
    uuid: uuid
